import nbformat
import json
from nbformat.v4 import new_notebook, new_code_cell, new_markdown_cell

def generate_notebook_bytes(chat_history: list, title: str = "Analysis Session") -> bytes:
    """
    Generates a Jupyter Notebook (.ipynb) from the chat history.
    """
    nb = new_notebook()
    
    # Add a title and intro block
    nb.cells.append(new_markdown_cell(f"# {title}\n*Generated by Assay System*"))
    
    for msg in chat_history:
        role = msg.get("role", "")
        content = msg.get("content", "")
        metadata = msg.get("metadata", {})
        
        if role == "user":
            nb.cells.append(new_markdown_cell(f"**User**: {content}"))
        elif role == "assistant":
            # Add the text explanation as markdown
            if content:
                nb.cells.append(new_markdown_cell(f"**Assistant**: {content}"))
            
            # If there's generated code, add it as an executable code cell
            if "code" in metadata and metadata["code"]:
                code = metadata["code"]
                # Strip markdown code block formatting if present
                if code.startswith("```python"):
                    code = code[9:]
                if code.startswith("```"):
                    code = code[3:]
                if code.endswith("```"):
                    code = code[:-3]
                code = code.strip()
                nb.cells.append(new_code_cell(code))
                
    nb_str = nbformat.writes(nb)
    return nb_str.encode('utf-8')
